version: "3.8"

services:
  # Serviço da API
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: backup-service-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      SECRET_USER: ${SECRET_USER}
      SECRET_PASS: ${SECRET_PASS}
      MONGO_URI: ${MONGO_URI}
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
