services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: backup-service-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      SECRET_USER: ${SECRET_USER}
      SECRET_PASS: ${SECRET_PASS}
      MONGO_URI: ${MONGO_URI}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$PORT/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy_net
      
networks:
  proxy_net:
    external: true
